version: "3.8"

services:
  trader:
    container_name: trader
    image: trader
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 4000:4000
    networks:
      - trader

  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - trader
  monitor:
    container_name: monitor
    image: hibiken/asynqmon
    command:
      - "--redis-addr=redis:6379"
    ports:
      - 8080:8080
    networks:
      - trader

networks:
  trader:
