version: "3.8"

services:
  trader:
    container_name: trader
    image: trader
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - nats
    networks:
      - trader

  nats:
    container_name: nats
    image: nats:2.7.0-alpine
    ports:
      - 4222:4222
    networks:
      - trader
networks:
  trader:
