# Image registry should be same as created in digitalocean_container_registry (infrastructure/main.tf)
apiVersion: skaffold/v2beta20
kind: Config
profiles:
  - name: production
    build:
      artifacts:
        - image: registry.digitalocean.com/trader-registry/proxy
          context: ./services/proxy
        - image: registry.digitalocean.com/trader-registry/nats
          context: ./services/nats
        - image: registry.digitalocean.com/trader-registry/web
          context: ./services/web
          docker:
            target: production
        - image: registry.digitalocean.com/trader-registry/exchange
          context: ./services/exchange
          docker:
            target: production
        - image: registry.digitalocean.com/trader-registry/notification
          context: ./services/notification
          docker:
            target: production
        - image: registry.digitalocean.com/trader-registry/strategy
          context: ./services/strategy
  - name: development
    build:
      artifacts:
        - image: registry.digitalocean.com/trader-registry/proxy
          context: ./services/proxy
        - image: registry.digitalocean.com/trader-registry/nats
          context: ./services/nats
        - image: registry.digitalocean.com/trader-registry/web
          context: ./services/web
          docker:
            target: development
          sync:
            manual:
              - src: "src/**/*.ts*"
                dest: .
        - image: registry.digitalocean.com/trader-registry/exchange
          context: ./services/exchange
          docker:
            target: development
          sync:
            manual:
              - src: "**/*.go"
                dest: .
        - image: registry.digitalocean.com/trader-registry/notification
          context: ./services/notification
          docker:
            target: development
          sync:
            manual:
              - src: "**/*.go"
                dest: .
        - image: registry.digitalocean.com/trader-registry/strategy
          context: ./services/strategy
          sync:
            manual:
              - src: "**/*.py"
                dest: .
deploy:
  helm:
    releases:
      - name: app
        chartPath: infrastructure/k8s
        valuesFiles:
          - infrastructure/k8s/values.yaml
          - infrastructure/k8s/env.yaml
        artifactOverrides:
          images.proxy: registry.digitalocean.com/trader-registry/proxy
          images.nats: registry.digitalocean.com/trader-registry/nats
          images.exchange: registry.digitalocean.com/trader-registry/exchange
          images.notification: registry.digitalocean.com/trader-registry/notification
          images.strategy: registry.digitalocean.com/trader-registry/strategy
          images.web: registry.digitalocean.com/trader-registry/web
portForward:
  - resourceName: proxy
    resourceType: service
    port: 8080
    localPort: 8080
