apiVersion: skaffold/v2beta20
kind: Config
profiles:
  - name: production
    build:
      artifacts:
        - image: proxy
          context: ./services/proxy
        - image: nats
          context: ./services/nats
        - image: web
          context: ./services/web
          docker:
            target: production
        - image: exchange
          context: ./services/exchange
          docker:
            target: production
        - image: notification
          context: ./services/notification
          docker:
            target: production
        - image: strategy
          context: ./services/strategy
  - name: development
    build:
      artifacts:
        - image: proxy
          context: ./services/proxy
        - image: nats
          context: ./services/nats
        - image: web
          context: ./services/web
          docker:
            target: development
          sync:
            manual:
              - src: "src/**/*.ts*"
                dest: .
        - image: exchange
          context: ./services/exchange
          docker:
            target: development
          sync:
            manual:
              - src: "**/*.go"
                dest: .
        - image: notification
          context: ./services/notification
          docker:
            target: development
          sync:
            manual:
              - src: "**/*.go"
                dest: .
        - image: strategy
          context: ./services/strategy
          sync:
            manual:
              - src: "**/*.py"
                dest: .
deploy:
  helm:
    releases:
      - name: app
        chartPath: infrastructure/k8s/app
        valuesFiles:
          - infrastructure/k8s/app/values.yaml
          - infrastructure/k8s/app/env.yaml
        artifactOverrides:
          images.proxy: proxy
          images.nats: nats
          images.exchange: exchange
          images.notification: notification
          images.strategy: strategy
          images.web: web
portForward:
  - resourceName: proxy
    resourceType: service
    port: 8080
    localPort: 8080
