apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - port: 4222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: {{ .Values.images.nats }}
          command: ["nats-server", "--user={{ .Values.env.nats.USER }}", "--pass={{ .Values.env.nats.PASS }}"]
          ports:
            - containerPort: 4222
