apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.application.repoURL }}
    targetRevision: HEAD
    path: {{ .Values.application.path }}
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
