name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/migrate-container-registry
env:
  APP_SECRETS: ${{ secrets.APP_SECRETS }}
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  CLUSTER_NAME: hypertrade-cluster
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure secrets
        run: echo "${{ env.APP_SECRETS }}" | base64 --decode > infrastructure/k8s/env.yaml

      - name: Install skaffold
        run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/

      - name: Install helm
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to Github Container Registry
        run: echo ${{ env.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}

      - name: Prepare environment
        run: scripts/prepare.sh production

      - name: Deploy to cluster with Skaffold
        run: skaffold run --profile production
